M48
; DRILL file {KiCad 9.0.4} date 2026-03-13T04:49:11-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-13T04:49:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X5.5344Y-3.3016
X5.5344Y-3.5291
T2
X3.937Y-3.8976
X5.6693Y-3.3858
M30
